import type { NextPage } from 'next'
import Head from 'next/head'


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mehdi Pouladgar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-4xl text-white text-center font-bold w-1/2 mx-auto'>
        <div className='text-left px-5'>
          <div>Hi,</div>
          <div>{"I'm"} <span className='name'>Mehdi</span></div>
        </div>
      </h1>
      <div className="p-4 flex justify-center">
        <div className='bg-gray-800 text-white rounded p-4 w-1/2'>
          <div className='flex items-center'>
            <div className='code-container-header-circle bg-red-500' />
            <div className='code-container-header-circle bg-amber-400' />
            <div className='code-container-header-circle bg-green-500' />
          </div>
          <pre className='mt-6'>
            <div className='flex'>
              <span className='c-number'>1</span>
              {"{"}
            </div>
            <div className=''>
              <div>
                <span className='c-number'>2</span>
                <span className='c-key'>{`"author"`}</span>: <span className='c-value'>{`"Mehdi Pouladgar"`}</span>,
              </div>
              <div>
                <span className='c-number'>3</span>
                <span className='c-key'>{`"description"`}</span>: <span className='c-value'>{`"Front-End Developer"`}</span>,
              </div>
              <div>
                <span className='c-number'>4</span>
                <span className='c-key'>{`"homepage"`}</span>: <span className='c-value'>{`"mehdi.dev"`}</span>,
              </div>
              <div>
                <span className='c-number'>5</span>
                <span className='c-key'>{`"coding"`}</span>: [
                <div className=''>
                  <div>
                    <span className='c-number'>6</span>
                    <div className='array-row'>
                      <div className='text-blue'>{`"JavaScript"`}</div>{", "}
                      <div className='text-blue'>{`"React"`}</div>{", "}
                      <div className='text-blue'>{`"TypeScript"`}</div>{", "}
                    </div>
                  </div>
                  <div>
                    <span className='c-number'>7</span>
                    <div className='array-row'>
                      <div className='text-blue'>{`"Next"`}</div>{", "}
                      <div className='text-blue'>{`"GraphQL"`}</div>{", "}
                      <div className='text-blue'>{`"Redux"`}</div>{", "}
                    </div>
                  </div>
                  <div>
                    <span className='c-number'>8</span>
                    <div className='array-row'>
                      <div className='text-blue'>{`"Sass"`}</div>{", "}
                      <div className='text-blue'>{`"Less"`}</div>{", "}
                      <div className='text-blue'>{`"TailwindCss"`}</div>{", "}
                    </div>
                  </div>
                  <div>
                    <span className='c-number'>9</span>
                    <div className='array-row'>
                      <div className='text-blue'>{`"Jest"`}</div>{", "}
                      <div className='text-blue'>{`"Cypress"`}</div>{", "}
                      <div className='text-blue'>{`"PWA"`}</div>
                    </div>
                  </div>
                </div>
                <div>
                  <span className='c-number'>10</span>
                  <div className='inline-block ml-6'>],</div>
                </div>
              </div>
              <div>
                <span className='c-number'>17</span>
                <span className='c-key'>{`"tools"`}</span>: [
                <div className=''>
                  <div>
                    <span className='c-number'>18</span>
                    <div className='array-row text-blue'>{`"Git"`}</div>,
                  </div>
                  <div>
                    <span className='c-number'>19</span>
                    <div className='array-row text-blue'>{`"Webpack"`}</div>,
                  </div>
                  <div>
                    <span className='c-number'>20</span>
                    <div className='array-row text-blue'>{`"Jira"`}</div>,
                  </div>
                  <div>
                    <span className='c-number'>21</span>
                    <div className='array-row text-blue'>{`"Trello"`}</div>,
                  </div>
                </div>
                <div>
                  <span className='c-number'>22</span>
                  <div className='inline-block ml-6'>]</div>
                </div>
              </div>
            </div>
            <div>
              <span className='c-number'>23</span>
              <div className='inline-block ml-2'>{"}"}</div>
            </div>
          </pre>
        </div>
      </div>
    </>
  )
}



export default Home
