import type { NextPage } from "next";
import Head from "next/head";
import { ProjectItem } from "@components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mehdi Pouladgar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full h-full">
        <div className="side" />
        <div className="relative pt-11 flex-1 flex flex-col">
          <div className="pl-5 border-b-2 pb-4 border-[#222]">
            <div className="font-bold text-2xl">Mehdi Pouladgar</div>
            <div className="text-primary mt-2">Front-end Developer</div>
          </div>
          <p className="text-sm text-gray-500 px-5 py-4">
            I am a Front end Developer working on JS Projects.
          </p>
          <div className="px-5">
            <div className="text-gray-200 text-sm mt-2">Top Skills</div>
            <div className="text-sm text-gray-500 flex flex-wrap gap-4 mt-2">
              <div>Javascript</div>
              <div>React</div>
              <div>NodeJS</div>
              <div>UI/UX</div>
            </div>
            <div className="text-gray-200 text-sm mt-6">Projects</div>

            <ProjectItem
              name="Rahito"
              description="Online Travel Booking"
              linkText="Rahito.com"
              linkUrl="https://rahito.com"
              logoUrl="/rahito.png"
            />
            <ProjectItem
              name="Lodge Roasters"
              description="Online Coffee"
              linkText="Lodgeroast.coffee"
              linkUrl="https://lodgeroast.coffee"
              logoUrl="/lodgeroast.png"
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;
