import type { NextPage } from "next";
import Head from "next/head";
import { CodeBlock, DownloadCV, Title } from "@components";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mehdi Pouladgar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title />
      <DownloadCV />
      <CodeBlock />
    </>
  );
};

export default Home;
